#!/usr/bin/env php
<?php

define('DS', DIRECTORY_SEPARATOR);
define('BASE_ROOT', __DIR__.DS);
define('PUB_ROOT', BASE_ROOT.'public'.DS);
define('APP_ROOT', BASE_ROOT.'app'.DS);

require 'vendor/autoload.php';

Pi\Cli\Application::bootstrap();
